# Generated by Django 5.2 on 2025-04-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('radio', 'Radio'), ('checkbox', 'Checkbox')], max_length=10)),
                ('choices', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pre_questions',
            },
        ),
    ]
